name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Sostituisci con il nome della tua branch, se diversa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Sostituisci con la tua versione di .NET

      - name: Change to Project Directory
        run: cd "ChatGPT Splitter Blazor"

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ChatGPT Splitter Blazor/publish/wwwroot  # Assicurati che questo percorso sia corretto
